-- Insert default global settings
INSERT INTO settings (
  setting_type,
  business_name,
  business_email,
  support_phone,
  business_address,
  theme,
  primary_color,
  font_size,
  border_radius,
  currency,
  timezone,
  language,
  booking_buffer_minutes,
  tax_percentage,
  invoice_prefix,
  wallet_enabled,
  online_payments_enabled,
  cash_payments_enabled,
  email_notifications_enabled,
  sms_notifications_enabled,
  push_notifications_enabled,
  booking_alerts_enabled,
  payment_alerts_enabled,
  review_alerts_enabled
)
VALUES (
  'global',
  'SKM Services Qatar',
  'info@skm-services.qa',
  '+974-4100-2200',
  '123 Pearl Street, West Bay, Doha, Qatar',
  'light',
  '#0052cc',
  'medium',
  'medium',
  'QAR',
  'Asia/Qatar',
  'en',
  30,
  5,
  'INV',
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true
)
ON CONFLICT DO NOTHING;
