import { NextRequest, NextResponse } from 'next/server';
import { supabase, supabaseAdmin, createBrowserClient } from '@/lib/supabase';
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/lib/database.types';

// CORS headers
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PATCH, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

// Handle CORS preflight
export async function OPTIONS() {
  return NextResponse.json({}, { headers: corsHeaders });
}

/**
 * POST /api/support/tickets
 * Create a new support ticket
 * 
 * Request body:
 * - source: 'customer_app' | 'branch_admin'
 * - user_name: string
 * - user_email: string
 * - user_phone: string
 * - issue_category: 'booking' | 'payment' | 'technical' | 'other'
 * - issue_description: string (min 20 chars)
 */
export async function POST(request: NextRequest) {
  try {
    const { source, user_name, user_email, user_phone, issue_category, issue_description } = await request.json();

    console.log('[API /support/tickets POST] Request:', {
      source,
      user_email,
      issue_category,
      descLength: issue_description?.length || 0,
    });

    // Validation
    if (!source || !['customer_app', 'branch_admin'].includes(source)) {
      return NextResponse.json({ error: 'Invalid source' }, { status: 400, headers: corsHeaders });
    }
    if (!user_name || user_name.trim().length < 3) {
      return NextResponse.json({ error: 'Name must be at least 3 characters' }, { status: 400, headers: corsHeaders });
    }
    if (!user_email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(user_email)) {
      return NextResponse.json({ error: 'Invalid email format' }, { status: 400, headers: corsHeaders });
    }
    if (!user_phone || !/^\d{7,}$/.test(user_phone.replace(/\D/g, ''))) {
      return NextResponse.json({ error: 'Phone must have at least 7 digits' }, { status: 400, headers: corsHeaders });
    }
    if (!issue_category || !['booking', 'payment', 'technical', 'other'].includes(issue_category)) {
      return NextResponse.json({ error: 'Invalid issue category' }, { status: 400, headers: corsHeaders });
    }
    if (!issue_description || issue_description.trim().length < 20) {
      return NextResponse.json({ error: 'Description must be at least 20 characters' }, { status: 400, headers: corsHeaders });
    }

    // Get token from Authorization header
    const authHeader = request.headers.get('Authorization');
    const token = authHeader?.replace('Bearer ', '');

    if (!token) {
      console.log('[API /support/tickets POST] No authorization token');
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers: corsHeaders });
    }

    console.log('[API /support/tickets POST] Token received, validating...');

    // Create a Supabase client with the user's token to validate it
    const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
    const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
    
    const userSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
    });

    // Validate the token by making a call as the authenticated user
    const { data: { user }, error: authError } = await userSupabase.auth.getUser();
    
    if (authError || !user) {
      console.log('[API /support/tickets POST] Auth error:', authError?.message || 'No user');
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers: corsHeaders });
    }

    console.log('[API /support/tickets POST] User authenticated:', user.id);

    // Insert ticket - ticket_number will be auto-generated by database trigger
    const ticketData = {
      source,
      user_id: user.id,
      user_name: user_name.trim(),
      user_email: user_email.trim(),
      user_phone: user_phone.trim(),
      issue_category,
      issue_description: issue_description.trim(),
      status: 'open',
      branch_id: source === 'branch_admin' ? user.id : null,
    };

    const { data: ticket, error: insertError } = await ((supabaseAdmin as any)
      .from('support_tickets')
      .insert([ticketData])
      .select('id, ticket_number, created_at')
      .single());

    if (insertError) {
      console.error('[API /support/tickets POST] Insert error:', insertError);
      return NextResponse.json({ error: 'Failed to create ticket' }, { status: 500, headers: corsHeaders });
    }

    console.log('[API /support/tickets POST] Ticket created:', {
      id: ticket?.id,
      ticket_number: ticket?.ticket_number,
      created_at: ticket?.created_at,
    });

    return NextResponse.json(
      {
        success: true,
        ticket_number: ticket?.ticket_number || 'TKT-2026-00001',
        id: ticket?.id || 'temp-id',
        created_at: ticket?.created_at || new Date().toISOString(),
        message: 'Your support ticket has been submitted. We will get back to you soon.',
      },
      { status: 201, headers: corsHeaders }
    );
  } catch (error) {
    console.error('[API /support/tickets POST] Error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500, headers: corsHeaders });
  }
}

/**
 * GET /api/support/tickets
 * Fetch support tickets
 * 
 * Query parameters:
 * - page: page number (default 1)
 * - status: filter by status (open, in_progress, resolved, closed)
 * - source: filter by source (customer_app, branch_admin)
 * - search: search by ticket number, user name, or email
 * 
 * For super admin: Returns all tickets with filters
 * For regular users: Returns only their own tickets
 */
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const page = Math.max(1, parseInt(searchParams.get('page') || '1', 10));
    const status = searchParams.get('status');
    const source = searchParams.get('source');
    const search = searchParams.get('search');

    const pageSize = 20;
    const offset = (page - 1) * pageSize;

    console.log('[API /support/tickets GET] Request:', {
      page,
      status,
      source,
      search,
    });

    // Get authenticated user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers: corsHeaders });
    }

    // Check if user is super admin
    const { data: userData, error: userError } = await supabaseAdmin
      .from('users')
      .select('role')
      .eq('id', user.id)
      .single();

    const isSuperAdmin = (userData as any)?.role === 'super_admin';

    console.log('[API /support/tickets GET] User:', {
      id: user.id,
      isSuperAdmin,
    });

    // Build query
    let query = (supabaseAdmin as any)
      .from('support_tickets')
      .select('*', { count: 'exact' });

    // If not super admin, filter by user_id
    if (!isSuperAdmin) {
      query = query.eq('user_id', user.id);
    }

    // Apply filters
    if (status) {
      query = query.eq('status', status);
    }
    if (source) {
      query = query.eq('source', source);
    }

    // Apply search filter (in memory after fetch due to Supabase limitations)
    const { data: tickets, count, error: queryError } = await query
      .order('created_at', { ascending: false })
      .range(offset, offset + pageSize - 1);

    if (queryError) {
      console.error('[API /support/tickets GET] Query error:', queryError);
      return NextResponse.json({ error: 'Failed to fetch tickets' }, { status: 500, headers: corsHeaders });
    }

    // Apply search filter in memory if provided
    let filteredTickets: any[] = tickets || [];
    if (search) {
      const searchLower = search.toLowerCase();
      filteredTickets = filteredTickets.filter((ticket: any) =>
        ticket.ticket_number?.toLowerCase().includes(searchLower) ||
        ticket.user_name?.toLowerCase().includes(searchLower) ||
        ticket.user_email?.toLowerCase().includes(searchLower)
      );
    }

    console.log('[API /support/tickets GET] Response:', {
      ticketsCount: filteredTickets.length,
      total: count,
      page,
      pageSize,
    });

    return NextResponse.json({
      tickets: filteredTickets,
      total_count: count || 0,
      page,
      page_size: pageSize,
      has_more: (offset + pageSize) < (count || 0),
    }, { headers: corsHeaders });
  } catch (error) {
    console.error('[API /support/tickets GET] Error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500, headers: corsHeaders });
  }
}
